[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions/"
